/**
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Pharmaceutical'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Pharmaceutical'));
  } else {
    // Browser globals (root is window)
    if (!root.PharmaTraceSupplyChainInformationNetworkApi) {
      root.PharmaTraceSupplyChainInformationNetworkApi = {};
    }
    root.PharmaTraceSupplyChainInformationNetworkApi.PharmaceuticalList = factory(root.PharmaTraceSupplyChainInformationNetworkApi.ApiClient, root.PharmaTraceSupplyChainInformationNetworkApi.Pharmaceutical);
  }
}(this, function(ApiClient, Pharmaceutical) {
  'use strict';




  /**
   * The PharmaceuticalList model module.
   * @module model/PharmaceuticalList
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>PharmaceuticalList</code>.
   * @alias module:model/PharmaceuticalList
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PharmaceuticalList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PharmaceuticalList} obj Optional instance to populate.
   * @return {module:model/PharmaceuticalList} The populated <code>PharmaceuticalList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('products')) {
        obj['products'] = ApiClient.convertToType(data['products'], [Pharmaceutical]);
      }
    }
    return obj;
  }

  /**
   * Contains the list of products
   * @member {Array.<module:model/Pharmaceutical>} products
   */
  exports.prototype['products'] = undefined;



  return exports;
}));


