/**
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PharmaTraceSupplyChainInformationNetworkApi);
  }
}(this, function(expect, PharmaTraceSupplyChainInformationNetworkApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PharmaTraceSupplyChainInformationNetworkApi.Profile();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Profile', function() {
    it('should create an instance of Profile', function() {
      // uncomment below and update the code to test Profile
      //var instance = new PharmaTraceSupplyChainInformationNetworkApi.Profile();
      //expect(instance).to.be.a(PharmaTraceSupplyChainInformationNetworkApi.Profile);
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new PharmaTraceSupplyChainInformationNetworkApi.Profile();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new PharmaTraceSupplyChainInformationNetworkApi.Profile();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new PharmaTraceSupplyChainInformationNetworkApi.Profile();
      //expect(instance).to.be();
    });

    it('should have the property twitterName (base name: "twitter_name")', function() {
      // uncomment below and update the code to test the property twitterName
      //var instance = new PharmaTraceSupplyChainInformationNetworkApi.Profile();
      //expect(instance).to.be();
    });

    it('should have the property linkedinName (base name: "linkedin_name")', function() {
      // uncomment below and update the code to test the property linkedinName
      //var instance = new PharmaTraceSupplyChainInformationNetworkApi.Profile();
      //expect(instance).to.be();
    });

    it('should have the property facebookName (base name: "facebook_name")', function() {
      // uncomment below and update the code to test the property facebookName
      //var instance = new PharmaTraceSupplyChainInformationNetworkApi.Profile();
      //expect(instance).to.be();
    });

    it('should have the property picture (base name: "picture")', function() {
      // uncomment below and update the code to test the property picture
      //var instance = new PharmaTraceSupplyChainInformationNetworkApi.Profile();
      //expect(instance).to.be();
    });

    it('should have the property stakeholderId (base name: "stakeholder_id")', function() {
      // uncomment below and update the code to test the property stakeholderId
      //var instance = new PharmaTraceSupplyChainInformationNetworkApi.Profile();
      //expect(instance).to.be();
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instance = new PharmaTraceSupplyChainInformationNetworkApi.Profile();
      //expect(instance).to.be();
    });

  });

}));
